import { Base } from "./Base.model";
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';

export class BaseParameter extends Base{
    ListID?: number[];
    SearchString?: string;
    Token?: string;
    IDString?: string;
    Password01?: string;
    Password02?: string;
    Password03?: string;
    TaiKhoan?: string;
    Year?: number;
    Page?: number;
    PageSize?: number;    
    ThanhVienID?: number;    
    ToChucID?: number;    
    DanhMucCompanyTinhTrangID?: number; 
    DanhMucQuyTrinhSanXuatPhanLoaiID?: number;    
    DanhMucDuAnID?: number;    
    DanhMucSanPhamID?: number;    
    ProvinceDataID?: number;    
    DistrictDataID?: number;    
    WardDataID?: number;    
    DanhMucUngDungID?: number;    
    CompanyExaminationID?: number;
    CompanyUserID?: number;
    CompanyInfoID?: number;
    DanhMucThanhVienID?: number;    
    StateAgencyID?: number;
    AgencyDepartmentID?: number;
    DanhMucChucDanhID?: number;
    DanhMucChucNangID?: number;
    DanhMucATTPLoaiHoSoID?: number;
    DanhMucATTPTinhTrangID?: number;
    DanhMucATTPXepLoaiID?: number;
    BienBanATTPParentID?: number;
    DocumentTemplateID?: number;
    PlanThamDinhID?: number;
    PlanTypeID?: number;
    DanhMucProductGroupID?: number;
    RegisterHarvestID?: number;
    RegisterHarvestItemsID?: number;
    SoThang?: number;
    Nam?: number;
    Thang?: number;
    SoDot?: number;
    NgayGhiNhan?: Date;
    BatDau?: Date;
    KetThuc?: Date;
    IsGoiY?: boolean;
    MatSort?: MatSort;    
    MatPaginator?: MatPaginator;    
}
